config {
    type: "incremental",
    uniqueKey: ["org_urn","service_type_id","state","created_date"],
    schema: 'inventory'
}

js {
  const incremental_hour = dataform.projectConfig.vars.incremental_hour;
}



select org_urn, 
service_type_id, 
state, 
count(*) as sim_count, 
DATE(CURRENT_TIMESTAMP) as created_date
from inventory.subscription_current 
group by org_urn, service_type_id, state, created_date